---
#bibliography:
#- 'bibliography.bib'
---

<br>
<br>

### Trinity College Dublin, The University of Dublin

<br>

## **Research Methods for Political Science A**

<br>

## \center Lectures


- [Methods Lecture](POU33011/MethodsMT01.pdf): Why do I need to learn about research methods?
- [Statistics Lecture](POU33011/StatisticsMT01.pdf): Why statistics? The problem of sampling
- [Methods Lecture](POU33011/MethodsMT02.pdf): Theories & concepts	
- [Statistics Lecture](POU33011/StatisticsMT02.pdf):
Univariate statistics: Measurement levels and measures of central tendency
- [Methods Lecture](POU33011/MethodsMT03.pdf): Variables, hypotheses & measurement	
- [Statistics Lecture](POU33011/StatisticsMT03.pdf):
Univariate statistics: Measures of dispersion and standard errors
- [Methods Lecture](POU33011/MethodsMT04.pdf): Measurement error and the research plan	
- [Statistics Lecture](POU33011/StatisticsMT04.pdf):
Univariate statistics: confidence intervals & significance testing
- [Methods Lecture](POU33011/MethodsMT05.pdf): Qualitative vs. quantitative research?	
- [Statistics Lecture](POU33011/StatisticsMT05.pdf):
Presenting data: tables and charts
- [Statistics Lecture (no "methods" this week) ](POU33011/StatisticsMT06.pdf): Bivariate statistics: cross tables and chi-square	
- [Statistics Lecture](POU33011/StatisticsMT06.pdf):
Bivariate statistics: cross tables and chi-square
- [Statistics Lecture (no "methods" this week) ](POU33011/StatisticsMT08a.pdf): Correlation	
- [Statistics Lecture](POU33011/StatisticsMT08b.pdf):
Bivariate statistics: t-tests
- Tuesday: Presentations 
- Thursday: Presentations 

- Tuesday: Presentations 

- Thursday: Presentations 
- [Methods Lecture](POU33011/MethodsMT11a.pdf): 
Experimental research

- [Methods Lecture (no statistics this week) ](POU33011/MethodsMT11b.pdf):
From experimental to quasi-experimental research
  
- [Methods Lecture ](POU33011/MethodsMT12.pptx): 
Formal analysis and rational choice

     Readings:  Osborne, M. J. (2003). An Introduction to Game Theory. Oxford: Oxford University Press. Chapter 1 & 2 available from http://www.economics.utoronto.ca/osborne/igt/intro.pdf and http://www.economics.utoronto.ca/osborne/igt/nash.pdf


- Thursday (29/11) Q&A, recap

**FRIDAY  30/11, 23:59: Final Paper due**
